### PR TITLE
General extra info API

### PR DESCRIPTION
**Pull request by christian-marie**
Not intended for merging (at least not yet), but to illustrate a possible solution to #10.

Naming leaves a lot to be desired, and I'm not sure if it's easy enough to work with.

### CODE REVIEW

**Comment by jkarni** [comment]
I like this. But I think it overlaps a lot with the possibilities create by having a pandoc-like(/based) intermediate representation. Or?

**Comment by christian-marie** [comment]
Certainly, but that would either be a breaking API change anyway when it is a thing, or we'll just deprecate these methods and replace them with cleaner ones?

I like the idea of a pandoc-like intermediate representation, but we shouldn't let nirvana get in the way of progress. I figure if we have to deprecate this bit of the API in future, we're at least not deprecating the simple use case (just using docs).

**Comment by christian-marie** [comment]
I'll clean this up tomorrow and request a merge for reals.

**Comment by jkarni** [comment]
I think you're right. This generally sounds good

**Comment by christian-marie** [comment]
Happy with this now.

This is way of adding whatever extra documentation you would like to any endpoint by specifying your own Action and pointing it at an endpoint with a Proxy that must be within the API.

See the updated example.

**Comment by alpmestan** [comment]
This is most likely the most convenient approach for this at this point. Could we rename `safeInfo` to just `info`? Unless there's an unsafe one somewhere else or something, we probably want the names to be as straightforward as possible.

Aside from that, LGTM.

**Comment by jkarni** [comment]
Cool approach!

**Pull request merged**
