### PR TITLE
Add DocIntro and DocNote types to allow extra docs

### PR DESCRIPTION
**Pull request by christian-marie**
This commit provides a way for a user to add information to either the
beginning of the output, and for a HasDoc instance to add extra sections to an
endpoint.

See example/greet.hs for usage of the Intro type.

### CODE REVIEW

**Comment by christian-marie** [comment]
This also changes the output slightly, to using atx headers. This was done so that sub-sections could be added that makes sense.  It may need to be tweaked a bit, perhaps lower levels of title, or perhaps we'd like a completely different header format. I like the idea of using headers for sections, though.

We were planning to use the DocNote type like this:

```haskell
instance (KnownSymbol scope, HasDocs sublayout)
            => HasDocs (TokenScope scope :> sublayout) where
    docsFor Proxy (endpoint, action) =
        docsFor sub (endpoint, action & headers %~ (|> "authorization")
                                      & notes %~ (++ [oauthNote, oauthNote]))
      where
        sub :: Proxy sublayout
        sub = Proxy 

        scope :: Proxy scope -> String
        scope = symbolVal

        oauthNote :: DocNote
        oauthNote = DocNote "Authorization"
            ["- Required scope: " <> scope Proxy]
```

Output is now as follows:

## On proper introductions.

Hello there.

As documentation is usually written for humans, it's often useful to introduce concepts with a few words.

## This title is below the last

You'll also note that multiple intros are possible.

## POST /greet

## Request Body:

``` javascript
{
    "msg": "Hello, haskeller!"
}
```

### Response:

 - Status code 201
 - If you use ?capital=true

``` javascript
{
    "msg": "HELLO, HASKELLER"
}
```

 - If you use ?capital=false

``` javascript
{
    "msg": "Hello, haskeller"
}
```

## GET /hello/:name

### Captures: 

- *name*: name of the person to greet

### GET Parameters: 

 - capital
     - **Values**: *true, false*
     - **Description**: Get the greeting message in uppercase (true) or not (false). Default is false.


### Response:

 - Status code 200
 - If you use ?capital=true

``` javascript
{
    "msg": "HELLO, HASKELLER"
}
```

 - If you use ?capital=false

``` javascript
{
    "msg": "Hello, haskeller"
}
```

## DELETE /greet/:greetid

### Captures: 

- *greetid*: identifier of the greet msg to remove

### Response:

 - Status code 204
 - No response body

**Comment by christian-marie** [comment]
I'm wondering if I should merge this or close it.

I've forgotten who, but someone mentioned that they'd like to do a rewrite before the next release? Shall we merge just in case that doesn't happen or leave it?

**Comment by alpmestan** [comment]
The only thing that bothers me is the way we introduce intros to docs, i.e by means of the `Intro` combinator. I'm perfectly fine with the rest. I'd be more comfortable not forcing this down people's throat but instead making the intro text an additional (but optional/possibly empty) argument of the `Proxy api -> API` function (`docsFor`). What do you think?

**Comment by christian-marie** [comment]
Sure. I can define a docsForWith and docsFor can just call that.

**Comment by alpmestan** [comment]
That would be perfect and something I would merge immediately! Thanks

**Comment by christian-marie** [comment]
Okay done, cleaned up some compile time warnings too.

**Pull request merged**
